# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: commands.proto
# Protobuf Python Version: 6.33.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    2,
    '',
    'commands.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x63ommands.proto\"9\n\tMcVersion\x12\r\n\x05major\x18\x01 \x01(\r\x12\r\n\x05minor\x18\x02 \x01(\r\x12\x0e\n\x06\x62ugfix\x18\x03 \x01(\r\"m\n\nRecipeStep\x12\x18\n\x04xPos\x18\x01 \x01(\x0e\x32\n.PositionX\x12\x13\n\x06yCount\x18\x02 \x01(\rH\x00\x88\x01\x01\x12\x1c\n\x04pump\x18\x03 \x01(\x0b\x32\t.PumpStepH\x01\x88\x01\x01\x42\t\n\x07_yCountB\x07\n\x05_pump\",\n\x08PumpStep\x12\x0f\n\x07pumpPos\x18\x01 \x01(\r\x12\x0f\n\x07seconds\x18\x02 \x01(\r\"\xb9\x01\n\x07Message\x12\n\n\x02id\x18\x01 \x01(\r\x12\x16\n\x04type\x18\x02 \x01(\x0e\x32\x08.CmdType\x12\x1b\n\x04step\x18\x03 \x01(\x0b\x32\x0b.RecipeStepH\x00\x12\x1a\n\x04xPos\x18\x04 \x01(\x0e\x32\n.PositionXH\x00\x12\x10\n\x06yCount\x18\x05 \x01(\rH\x00\x12\x15\n\x0bstopDefault\x18\x06 \x01(\x08H\x00\x12\x1d\n\x08pumpStep\x18\x07 \x01(\x0b\x32\t.PumpStepH\x00\x42\t\n\x07payload\"\x7f\n\x08Response\x12\n\n\x02id\x18\x01 \x01(\r\x12\x1b\n\x04type\x18\x02 \x01(\x0e\x32\r.ResponseType\x12 \n\x07version\x18\x03 \x01(\x0b\x32\n.McVersionH\x00\x88\x01\x01\x12\x12\n\x05\x65rror\x18\x04 \x01(\rH\x01\x88\x01\x01\x42\n\n\x08_versionB\x08\n\x06_error*o\n\x07\x43mdType\x12\x11\n\rCMD_UNDEFINED\x10\x00\x12\x0f\n\x0bHELLO_THERE\x10\x01\x12\x08\n\x04STOP\x10\x02\x12\x0f\n\x0bRECIPE_STEP\x10\x03\x12\n\n\x06MOVE_X\x10\x04\x12\n\n\x06MOVE_Y\x10\x05\x12\r\n\tPUMP_STEP\x10\x06*J\n\x0cResponseType\x12\x11\n\rRSP_UNDEFINED\x10\x00\x12\x08\n\x04\x44ONE\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x12\x12\n\x0e\x45MERGENCY_STOP\x10\x03*h\n\tPositionX\x12\x0b\n\x07INVALID\x10\x00\x12\x07\n\x03ONE\x10\x01\x12\x07\n\x03TWO\x10\x02\x12\t\n\x05THREE\x10\x03\x12\x08\n\x04\x46OUR\x10\x04\x12\x08\n\x04\x46IVE\x10\x05\x12\x07\n\x03SIX\x10\x06\x12\t\n\x05SEVEN\x10\x07\x12\t\n\x05\x46INAL\x10\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'commands_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CMDTYPE']._serialized_start=551
  _globals['_CMDTYPE']._serialized_end=662
  _globals['_RESPONSETYPE']._serialized_start=664
  _globals['_RESPONSETYPE']._serialized_end=738
  _globals['_POSITIONX']._serialized_start=740
  _globals['_POSITIONX']._serialized_end=844
  _globals['_MCVERSION']._serialized_start=18
  _globals['_MCVERSION']._serialized_end=75
  _globals['_RECIPESTEP']._serialized_start=77
  _globals['_RECIPESTEP']._serialized_end=186
  _globals['_PUMPSTEP']._serialized_start=188
  _globals['_PUMPSTEP']._serialized_end=232
  _globals['_MESSAGE']._serialized_start=235
  _globals['_MESSAGE']._serialized_end=420
  _globals['_RESPONSE']._serialized_start=422
  _globals['_RESPONSE']._serialized_end=549
# @@protoc_insertion_point(module_scope)
