name: Ultramat-CI-CD

on:
  push:
    branches:
      - main

jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build-step
        run: | 
          # Build docker file
          docker build -t docker-ultra-build .
          # Mount project
          docker run -v $(pwd):/ultramat docker-ultra-build bash "./dewit.sh"