name: Ultramat-CI-CD

on:
  push:
    branches:
      - main

jobs:
  build:
    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build-step
        run: | 
          # Build docker file
          docker build -t docker-ultra-build .
          # Mount project
          docker run -v $(PWD):/ultramat docker-ultra-build /bin/bash -c "cd ultramat && ./dewit.sh"
