name: Ultramat-CI-CD

on:
  push:
    tags:
      - "v*.*.*"

env:
  TARGET_x86_64: "Ultramat.x86_64"
  TARGET_arm64: "Ultramat.aarch64"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Get Release Version
        run: echo "RELEASE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Pull Docker Image from Docker Hub
        run: |
          docker pull kleinspeedy/ultramat-cross-builder:latest

      - name: build x86_64 and arm64 targets
        run: | 
          docker run --rm -v ${{ github.workspace }}:/ultramat kleinspeedy/ultramat-cross-builder:latest \
          /bin/bash -c "./scripts/release_builder.sh"

      - name: rename and move binaries
        run: |
          sudo chown -R $(whoami):$(whoami) build/ arm-build/
          mv build/$TARGET_x86_64 $TARGET_x86_64-${{ env.RELEASE_TAG }}
          mv arm-build/$TARGET_arm64 $TARGET_arm64-${{ env.RELEASE_TAG }}

      - name: upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: binaries
          path: Ultramat.*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: binaries

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            Ultramat.*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
